### ISSUE TITLE
Example of using Rgb in theme?

### ISSUE THREAD

**Issue by Diaoul** [aome510/spotify-player#177]
**Describe the bug**
I cannot get the right TOML to have the RGB struct unpack the actual value I'd like to use.

**To Reproduce**
```toml
[themes.component_style]
playback_album = { fg = {r = 214, g = 93, b = 13} }
```
```
❯ spotify_player
Error: TOML parse error at line 28, column 25
   |
28 | playback_album = { fg = {r = 214, g = 93, b = 13} }
   |                         ^^^^^^^^^^^^^^^^^^^^^^^^^
wanted exactly 1 element, more than 1 element
```

**Expected behavior**
I can specify the RGB code in that format, or even better, use the hex code

**Environment**

- OS: Arch
- Application version: 0.13.1
