### ISSUE TITLE
Enter doesn't work for on the Search  Page

### ISSUE THREAD

**Issue by BinaryFly** [aome510/spotify-player#208]
When I go to the search page I can't press enter to search, I found out this is the way search by watching the demo on youtube. I can exit the "insert mode" from the search bar by pressing Ctrl + I but even then when I press enter nothing happens. Am I doing something wrong or am I invoking the search in the wrong way?

- OS: Fedora 38
- Application version: release
- Application features: pulseaudio backend

**Additional context**
the following is my app.toml:
```toml
theme = "default"
client_id = "<-private-client-id->"
client_port = 8888
playack_format = "{track} • {artists}\n{album}\n{metadata}"
notify_format = { summary = "{track} • {artists}", body = "{album}" }
# the default `copy_command` is based on the OS
copy_command = { command = "pbcopy", args = [] } # macos
# copy_command = { command = "xclip", args = ["-sel", "c"] } # linux
# copy_command = { command = "clip", args = [] } # windows
app_refresh_duration_in_ms = 32
playback_refresh_duration_in_ms = 0
cover_image_refresh_duration_in_ms = 2000
page_size_in_rows = 20
track_table_item_max_len = 32
enable_media_control = false
enable_streaming = true
enable_cover_image_cache = true
default_device = "spotify-player"
play_icon = "▶"
pause_icon = "▌▌"
liked_icon = "♥"
playback_window_position = "Top"
cover_img_length = 9
cover_img_width = 5
playback_window_width = 6

[device]
name = "spotify-player"
device_type = "speaker"
volume = 100
bitrate = 160
audio_cache = false
```

and my keymap.toml:

```toml
[[keymaps]]
command = "FocusNextWindow"
key_sequence = "l"
[[keymaps]]
command = "FocusPreviousWindow"
key_sequence = "h"
[[keymaps]]
command = "PageSelectNextOrScrollDown"
key_sequence = "C-d"
[[keymaps]]
command = "PageSelectPreviousOrScrollUp"
key_sequence = "C-u"
```
