### ISSUE TITLE
what things can i do to make the start time of spotify-player more fast

### ISSUE THREAD

**Issue by RioAngele** [aome510/spotify-player#217]
when i start this software,i need a lot of time to wait for it.
Is my `app.toml` having some problems？
```toml
theme = "default"
client_id = "~~"
client_port ="~~"
playback_format = "{track} • {artists}\n{album}\n{metadata}"
notify_format = { summary = "{track} • {artists}", body = "{album}" }
copy_command = { command = "xclip", args = ["-sel", "c"] } # linux
app_refresh_duration_in_ms = 0
playback_refresh_duration_in_ms = 0
page_size_in_rows = 20
track_table_item_max_len = 32
enable_media_control = false
enable_streaming = false
enable_cover_image_cache = false
[device]
name = "spotify-player"
device_type = "speaker"
volume = 100
bitrate = 320
audio_cache = false
```
i use arch linux
how to make fast to start up
