### ISSUE TITLE
`Bottom` with `Hidden` borders causes useless padding

### ISSUE THREAD

**Issue by apprehensions** [aome510/spotify-player#331]
![20240106_151324](https://github.com/aome510/spotify-player/assets/47404953/22b70dd0-0d04-48a3-8f5d-5a3674e48cc4)
![20240106_151337](https://github.com/aome510/spotify-player/assets/47404953/fc147ce0-df7f-489e-a665-8791e365c8ff)
^ The highlighted selection is the useless padding introduced when there is no border.

```toml
border_type = "Hidden"
playback_window_position = "Bottom"
playback_window_width = 4
```
