### ISSUE TITLE
Remap key to key combination

### ISSUE THREAD

**Issue by repparw** [aome510/spotify-player#428]
I'm thinking how to bind y to the equivalent of 'a 5'. So, current song, copy link.
I think either having it so you can bind to a sequence of commands, or bind a key to a sequence of keys would be nice.
Something like
[[keymaps]]
command = "ShowActionsOnCurrentTrack; CopyTrackLink"
key_sequence = "y"
or
[[keymaps]]
command = "a 5" // maybe a different name instead of command? idk
key_sequence = "y"

**Comment by aome510** [comment]
It's better to define a separate mapping for actions:

```toml
[[actions]]
action = "GoToTrackRadio"
key = "r"

[[actions]]
action = "AddToLikedTracks"
key = "y"
```
