### ISSUE TITLE
Cover image is duplicated when playback window is at bottom

### ISSUE THREAD

**Issue by diegoulloao** [aome510/spotify-player#498]
**Describe the bug**
A duplicated cover image appears inside the playlist when the playback window position is at bottom.

**To Reproduce**
1. Set playback window at bottom: `playback_window_position = "Bottom"`
2. Play something

**Expected behaviour**
See a single image in the playback window, no duplicated ones.

**Screenshots**
<img width="1440" alt="Screenshot 6" src="https://github.com/aome510/spotify-player/assets/45423661/fd24c50a-aa96-40d9-97bb-f32e82fee105">

**Environment**

- OS: macOs
- Application version: 0.19.1 (up to date version)
- Application features: image, daemon

**Additional context**
```toml
theme = "neofusion"
client_id = "secret"
enable_media_control = true
cover_img_length = 14
page_size_in_rows = 14
playback_window_position = "Bottom"
play_icon = ""
pause_icon = ""

[device]
name = "spotify-player"
device_type = "speaker"
volume = 100
bitrate = 320
audio_cache = false
```

** Only happening in Kitty terminal (0.35.2).
