### ISSUE TITLE
[Feature]: Ability to further customize layout

### ISSUE THREAD

**Issue by NickTheWilder** [aome510/spotify-player#535]
**Describe the solution you'd like**
I personally never use Albums & Artists in Spotify, only playlist to sort songs. It would be nice to be able to 
1. Remove columns
2. Add different columns to replace them (seems more complicated but a nice to have)

**Describe alternatives you've considered**
Adjusting the layout of playlists/albums in the config to potentially hide the columns

ℹ️ FWIW the layout settings don't work for me, Win11 - PowerShell v7.4.4 - v0.19.1
Current settings: 
```toml
# omitted other settings above
[layout]
library = { playlist_percent = 75, album_percent = 12 }
playback_window_position = "Top"
```

**Additional context**
I'd start working on this if I had experience with Rust and open a PR but no experience here. Really enjoy what's going on so far.

Example to further describe what I'm talking about

Current view:
![image](https://github.com/user-attachments/assets/00cc9e86-5cce-4152-a525-d2815cc2b4a9)

Proposed view: (or smth similar)
![image](https://github.com/user-attachments/assets/7c2e5107-27dc-4ded-8d59-9c06e8dfc669)
