### ISSUE TITLE
More vim-like navigation

### ISSUE THREAD

**Issue by weston-harper-rox** [aome510/spotify-player#720]
**Is your feature already implemented in the latest `master`?**
No

**Is your feature request related to a problem? Please describe.**
My muscle memory is pretty built around vim motions, which are for the most part honored by the client. However, I constantly find myself hitting 'h' or 'l' and cursing to myself because I just swapped to the lyrics page.

**Describe the solution you'd like**
- 'h', 'j', 'k', and 'l' navigate up, down, left, and right _always_ and the lyrics page is accessible through `'g <something>'`.
- 'h', 'j', 'k', and 'l' navigate between panes as an alternative to tab/shift-tab.

**Describe alternatives you've considered**
None really, I love the tool and use it all the time!

**Additional context**
N/A

**Comment by aome510** [comment]
> 'h', 'j', 'k', and 'l' navigate up, down, left, and right always and the lyrics page is accessible through 'g <something>'.
> 'h', 'j', 'k', and 'l' navigate between panes as an alternative to tab/shift-tab.

you can re-map the default keybindings by following https://github.com/aome510/spotify-player/blob/master/docs/config.md#keymaps

**Comment by janekx21** [comment]
You could provide a vim `keymaps.toml`. This would be very helpful ^^

**Comment by l3d00m** [comment]
See my config at https://github.com/l3d00m/dotfiles/blob/main/dot_config/spotify-player/keymap.toml

```toml
[[keymaps]]
command = "SelectPreviousOrScrollUp" # up
key_sequence = "k"

[[keymaps]]
command = "SelectNextOrScrollDown" # down
key_sequence = "j"

[[keymaps]]
command = "ChooseSelected" # enter context
key_sequence = "l"

[[keymaps]]
command = "PreviousPage" # go back
key_sequence = "h"


[[keymaps]]
command = "FocusPreviousWindow" # left (pane)
key_sequence = "w h"

[[keymaps]]
command = "FocusNextWindow" # right (pane)
key_sequence = "w l"

# Move LyricsPage to a 'g l' shortcut instead of 'l'
[[keymaps]]
command = "LyricsPage"
key_sequence = "g l"
```

I did something like this. Enter a context with `l`, leave it with `h`. Also use `w` followed by `h` or `l` to navigate between panes. Not sure if that intuitive for everyone or just for me.
