### ISSUE TITLE
Parameterized `Seek{Backward,Forward}` command (for keymaps)

### ISSUE THREAD

**Issue by sandersantema** [aome510/spotify-player#724]
**Is your feature already implemented in the latest `master`?**
Please go through the [Features README page](https://github.com/aome510/spotify-player?tab=readme-ov-file#features) to make sure your request feature hasn't been implemented.
No.
**Is your feature request related to a problem? Please describe.**
Currently I use the official spotify client together with spicetify and some custom code for their vim like keybindings extension. The custom code allows me to seek forward/ backward by an amount specified by me, that is, I use `w` and `e` to seek backwards and forwards by 100secs respectively and `W` and `E` to seek backwards and forwards by 20secs respectively. I'd like to be able to do the same in spotify-player. If you're wondering what my use case is: music discovery, I check out a lot of songs and often don't need to hear the whole song to know whether it is worth listening to in detail, quickly skipping through a song and hearing some snippets is enough.

**Describe the solution you'd like**
I'd like a configurable seek amount, something like:
```toml
[[keymaps]]
command = { SeekBackwardBy = { secs = 100 } }
key_sequence = "w"

[[keymaps]]
command = { SeekBackwardBy = { secs = 20 } }
key_sequence = "W"

[[keymaps]]
command = { SeekForwardBy = { secs = 100 } }
key_sequence = "e"

[[keymaps]]
command = { SeekForwardBy = { secs = 20 } }
key_sequence = "E"
```

Or alternatively just by changing the original `Seek{Backward,Forward}` commands, but I think both commands are useful as not every body will need a configurable seek amount.

**Describe alternatives you've considered**
I've considered seeking by a configurable amount using `playerctl` but that would require support for executing shell commands using keybindings, which isn't supported afaik.
